### ISSUE TITLE
Node enhancement request

### ISSUE THREAD

**Issue by Amazon90** [kaibioinfo/ComfyUI_AdvancedRefluxControl#14]
Please add image control functionality similar to the following nodes.
https://github.com/tanglup/Comfyui_Flux_Style_Adjust

**Comment by kaibioinfo** [comment]
Did you tried if that works? For me the code doesn't make much sense to be honest.

**Comment by Amazon90** [comment]
> Did you tried if that works? For me the code doesn't make much sense to be honest.

I apologize for only noticing this now. I think it would be great if we could specify the migration of specific image features. Additionally, in my tests, it indeed did not work as you mentioned. It would be fantastic if you could implement this feature!

![1](https://github.com/user-attachments/assets/0bebe0c2-d91b-46eb-b085-aa9f7ea210a4)

**Comment by kaibioinfo** [comment]
I once tried something similar: computing the singular vectors of the conditioning tokens and then check if certain singular vectors corresponds to style, color, composition and so on.
While there are indeed singular vectors that encode composition but not style (so you can extract composition-only), there is nothing similar for style.
I might still do some experiments, but I'm rather skeptical if there is an easy solution for this. If style is not defined in some high-eigenvalue vector then it is probably not possible to extract it.

**Comment by Amazon90** [comment]
> I once tried something similar: computing the singular vectors of the conditioning tokens and then check if certain singular vectors corresponds to style, color, composition and so on.
> While there are indeed singular vectors that encode composition but not style (so you can extract composition-only), there is nothing similar for style.
> I might still do some experiments, but I'm rather skeptical if there is an easy solution for this. If style is not defined in some high-eigenvalue vector then it is probably not possible to extract it.

Since the official training method for the model hasn’t been disclosed, finding effective adjustments is indeed challenging. Nevertheless, I appreciate the effort you’ve put into this work.

**Comment by Amazon90** [comment]
> I once tried something similar: computing the singular vectors of the conditioning tokens and then check if certain singular vectors corresponds to style, color, composition and so on.
> 
> While there are indeed singular vectors that encode composition but not style (so you can extract composition-only), there is nothing similar for style.
> 
> I might still do some experiments, but I'm rather skeptical if there is an easy solution for this. If style is not defined in some high-eigenvalue vector then it is probably not possible to extract it.  

https://github.com/envy-ai/ComfyUI-ConDelta

This custom node also works on conditional pipelines, and perhaps you can find a method from it to separate image features for using Redux to reference different parts.
