### ISSUE TITLE
Hi, your "Style Model Apply Advanced" Node replaced the famous KJNode Style apply node...

### ISSUE THREAD

**Issue by LiJT** [kaibioinfo/ComfyUI_AdvancedRefluxControl#2]
This is the original node in my workflow
![2](https://github.com/user-attachments/assets/4dd63c52-a527-4e20-9329-a37e3a4318b5)

After installing your node, now your node taken his place... I guess it shared the same name for some reason?
![1](https://github.com/user-attachments/assets/466a4f22-a2bb-4472-89a5-01f053a7fafd)

Can you maybe change your node name to some other name to avoid conflict? 
We all love Kijai but i think he made that node first so if you change that node name would greatly apprcieciated
https://github.com/kijai/ComfyUI-KJNodes

**Comment by kaibioinfo** [comment]
The "clipWeight" parameter is indeed equivalent to his "strength" parameter. 

I renamed the node to "ReduxAdvanced" to avoid confusion/conflicting names. This also has the advantage that I don't have to hurry to find out how to get patch size and image size from the vision model - at the moment my node is only working for Redux but not for other unclip models.
