### ISSUE TITLE
You made a spelling mistake, I think you mean Redux

### ISSUE THREAD

**Issue by RamonGuthrie** [kaibioinfo/ComfyUI_AdvancedRefluxControl#4]
it's Redux instead of Reflux, I don't want people missing out on this great useful node

**Comment by kaibioinfo** [comment]
Haha, ouch. It was not on purpose. I THOUGHT BFL called it "Reflux" on purpose, because... why would you want to miss this joke?
I don't think I can rename the repository without making people angry. But I will at least try to rename the node in the manager ^^°°°

**Comment by RamonGuthrie** [comment]
Well done on making and creating this useful node so quickly 👏🏾
